import type { CalculatorInput } from "./types";

/** Sensible US planning defaults. Rates are decimal (0.026 = 2.6%). */
export const DEFAULT_INPUT: CalculatorInput = {
  currentAge: 58,
  retirementAge: 65,
  planToAge: 95,
  currentSavings: 720000,
  annualContribution: 18000,
  preRetirementReturn: 0.07,
  postRetirementReturn: 0.05,
  inflationRate: 0.026,
  healthcareInflationRate: 0.052,
  lifestyleSpendToday: 62000,
  healthcareSpendToday: 8400,
  socialSecurityAnnual: 28800,
  socialSecurityStartAge: 67,
  pensionAnnual: 0,
  pensionStartAge: 65,
  partTimeAnnualIncome: 22000,
  partTimeStartAge: 65,
  partTimeEndAge: 72,
  goGoEndAge: 75,
  slowGoEndAge: 85,
  goGoLifestyleMultiplier: 1.08,
  slowGoLifestyleMultiplier: 0.82,
  noGoLifestyleMultiplier: 0.62,
  longTermCareAnnual: 18000,
  longTermCareStartAge: 85,
  seniorHomeRentAnnual: 0,
  seniorHomeStartAge: 75,
  nursingHomeRentAnnual: 0,
  nursingHomeStartAge: 85,
  ccrcRentAnnual: 0,
  ccrcStartAge: 75,
};

export const FIELD_META: Record<
  keyof CalculatorInput,
  { label: string; hint?: string; group: string; kind: "age" | "money" | "percent" | "multiplier" }
> = {
  currentAge: { label: "Current age", group: "timeline", kind: "age" },
  retirementAge: { label: "Full-time work ends", group: "timeline", kind: "age" },
  planToAge: { label: "Plan through age", hint: "Longevity target, not a prediction.", group: "timeline", kind: "age" },
  currentSavings: { label: "Current retirement savings", group: "savings", kind: "money" },
  annualContribution: { label: "Annual savings until retirement", hint: "Same dollar amount each year. Inflation raises spending, not this deposit.", group: "savings", kind: "money" },
  partTimeAnnualIncome: { label: "Part-time / side-hustle income", hint: "Today’s dollars, after retirement.", group: "work", kind: "money" },
  partTimeStartAge: { label: "Part-time starts", group: "work", kind: "age" },
  partTimeEndAge: { label: "Part-time ends", hint: "Last year with this income.", group: "work", kind: "age" },
  socialSecurityAnnual: { label: "Social Security / year", hint: "Today’s dollars.", group: "income", kind: "money" },
  socialSecurityStartAge: { label: "Social Security starts", group: "income", kind: "age" },
  pensionAnnual: { label: "Pension / year", group: "income", kind: "money" },
  pensionStartAge: { label: "Pension starts", group: "income", kind: "age" },
  lifestyleSpendToday: { label: "Lifestyle spending / year", hint: "Housing, food, travel — not medical.", group: "spending", kind: "money" },
  healthcareSpendToday: { label: "Healthcare spending / year", hint: "Premiums + out-of-pocket today.", group: "spending", kind: "money" },
  longTermCareAnnual: { label: "Long-term care / year", hint: "In-home or extra support. Skipped once nursing or CCRC rent starts.", group: "spending", kind: "money" },
  longTermCareStartAge: { label: "Long-term care starts", group: "spending", kind: "age" },
  seniorHomeRentAnnual: { label: "Senior home rental / year", hint: "Independent living. Today’s dollars.", group: "housing", kind: "money" },
  seniorHomeStartAge: { label: "Senior rental starts", group: "housing", kind: "age" },
  nursingHomeRentAnnual: { label: "Nursing home / year", hint: "Replaces senior rental from this age.", group: "housing", kind: "money" },
  nursingHomeStartAge: { label: "Nursing home starts", group: "housing", kind: "age" },
  ccrcRentAnnual: { label: "Continuing care rent / year", hint: "CCRC monthly fees, annualized. Takes priority if set.", group: "housing", kind: "money" },
  ccrcStartAge: { label: "Continuing care starts", group: "housing", kind: "age" },
  inflationRate: { label: "General inflation", group: "assumptions", kind: "percent" },
  healthcareInflationRate: { label: "Healthcare inflation", group: "assumptions", kind: "percent" },
  preRetirementReturn: { label: "Return before retirement", group: "assumptions", kind: "percent" },
  postRetirementReturn: { label: "Return in retirement", group: "assumptions", kind: "percent" },
  goGoEndAge: { label: "Go-go years end", hint: "Higher travel and activity, through this age.", group: "phases", kind: "age" },
  slowGoEndAge: { label: "Slow-go years end", hint: "Through this age, then no-go years begin.", group: "phases", kind: "age" },
  goGoLifestyleMultiplier: { label: "Go-go lifestyle factor", group: "phases", kind: "multiplier" },
  slowGoLifestyleMultiplier: { label: "Slow-go lifestyle factor", group: "phases", kind: "multiplier" },
  noGoLifestyleMultiplier: { label: "No-go lifestyle factor", group: "phases", kind: "multiplier" },
};
