import type { CalculatorInput } from "./types";

/** Sensible US planning defaults. Rates are decimal (0.026 = 2.6%). */
export const DEFAULT_INPUT: CalculatorInput = {
  currentAge: 58,
  retirementAge: 65,
  planToAge: 95,
  twoPerson: false,
  partnerCurrentAge: 56,
  partnerRetirementAge: 65,
  partnerPlanToAge: 95,
  partnerSocialSecurityAnnual: 0,
  partnerSocialSecurityStartAge: 67,
  partnerPensionAnnual: 0,
  partnerPensionStartAge: 65,
  partnerPensionCola: true,
  pensionSurvivorPercent: 0,
  partnerPensionSurvivorPercent: 0,
  partnerPartTimeAnnualIncome: 0,
  partnerPartTimeStartAge: 65,
  partnerPartTimeEndAge: 72,
  partnerHealthcareSpendToday: 0,
  partnerLongTermCareAnnual: 0,
  partnerLongTermCareStartAge: 85,
  partnerNursingHomeRentAnnual: 0,
  partnerNursingHomeStartAge: 85,
  survivorLifestyleFactor: 0.75,
  lifeInsuranceLump: 0,
  currentSavings: 720000,
  annualContribution: 18000,
  savingsGrowWithInflation: false,
  preRetirementReturn: 0.07,
  postRetirementReturn: 0.05,
  inflationRate: 0.026,
  healthcareInflationRate: 0.052,
  lifestyleSpendToday: 62000,
  healthcareSpendToday: 8400,
  socialSecurityAnnual: 28800,
  socialSecurityStartAge: 67,
  pensionAnnual: 0,
  pensionStartAge: 65,
  pensionCola: true,
  partTimeAnnualIncome: 22000,
  partTimeStartAge: 65,
  partTimeEndAge: 72,
  partTimeAnnualInvestment: 0,
  partTimeInvestmentReturn: 0,
  goGoEndAge: 75,
  slowGoEndAge: 85,
  goGoLifestyleMultiplier: 1.08,
  slowGoLifestyleMultiplier: 0.82,
  noGoLifestyleMultiplier: 0.62,
  longTermCareAnnual: 18000,
  longTermCareStartAge: 85,
  seniorHomeRentAnnual: 0,
  seniorHomeStartAge: 75,
  nursingHomeRentAnnual: 0,
  nursingHomeStartAge: 85,
  ccrcRentAnnual: 0,
  ccrcStartAge: 75,
};

export const FIELD_META: Record<
  keyof CalculatorInput,
  { label: string; hint?: string; group: string; kind: "age" | "money" | "percent" | "multiplier" | "toggle" }
> = {
  currentAge: { label: "Current age", group: "timeline", kind: "age" },
  retirementAge: { label: "Full-time work ends", group: "timeline", kind: "age" },
  planToAge: { label: "Plan through age", hint: "Longevity target, not a prediction. First person when two persons is on.", group: "timeline", kind: "age" },
  twoPerson: {
    label: "Two persons",
    hint: "Off = one person. On = a partner card with their income, a second plan-through age, and survivor years. One nest egg and one set of market returns.",
    group: "timeline",
    kind: "toggle",
  },
  partnerCurrentAge: { label: "Partner’s current age", group: "timeline", kind: "age" },
  partnerRetirementAge: {
    label: "Partner full-time work ends",
    hint: "Household drawdowns start when the first of you leaves full-time work. Yearly saving continues until the later work-end.",
    group: "timeline",
    kind: "age",
  },
  partnerPlanToAge: { label: "Partner plan through age", hint: "Second longevity target, not a prediction.", group: "timeline", kind: "age" },
  partnerSocialSecurityAnnual: { label: "Partner Social Security / year", hint: "Today’s dollars, with COLA. Leave at 0 to skip.", group: "partner", kind: "money" },
  partnerSocialSecurityStartAge: { label: "Partner Social Security starts", group: "partner", kind: "age" },
  partnerPensionAnnual: { label: "Partner pension / year", hint: "Leave at 0 to skip.", group: "partner", kind: "money" },
  partnerPensionStartAge: { label: "Partner pension starts", group: "partner", kind: "age" },
  partnerPensionCola: {
    label: "Partner pension COLA",
    hint: "On = this pension rises with inflation. Off = a fixed annual amount.",
    group: "partner",
    kind: "toggle",
  },
  pensionSurvivorPercent: {
    label: "Your pension that continues",
    hint: "Share of the first person’s pension paid after they die. 0% = it ends.",
    group: "partner",
    kind: "percent",
  },
  partnerPensionSurvivorPercent: {
    label: "Partner pension that continues",
    hint: "Share of the partner’s pension paid after they die. 0% = it ends.",
    group: "partner",
    kind: "percent",
  },
  partnerPartTimeAnnualIncome: { label: "Partner part-time / side-hustle", hint: "Today’s dollars. A second wage window; not pooled into the first.", group: "partner", kind: "money" },
  partnerPartTimeStartAge: { label: "Partner part-time starts", group: "partner", kind: "age" },
  partnerPartTimeEndAge: { label: "Partner part-time ends", group: "partner", kind: "age" },
  partnerHealthcareSpendToday: { label: "Partner healthcare / year", hint: "Premiums + out-of-pocket today. 0 skips a second healthcare line.", group: "partner", kind: "money" },
  partnerLongTermCareAnnual: { label: "Partner long-term care / year", hint: "In-home or extra support. Skipped once their nursing rent starts.", group: "partner", kind: "money" },
  partnerLongTermCareStartAge: { label: "Partner long-term care starts", group: "partner", kind: "age" },
  partnerNursingHomeRentAnnual: { label: "Partner nursing home / year", hint: "Added on top of household living if they go into care and you are still at home.", group: "partner", kind: "money" },
  partnerNursingHomeStartAge: { label: "Partner nursing home starts", group: "partner", kind: "age" },
  survivorLifestyleFactor: {
    label: "Survivor lifestyle factor",
    hint: "Scales household lifestyle after the first death. 0.75 means 75% of the two-person lifestyle.",
    group: "partner",
    kind: "multiplier",
  },
  lifeInsuranceLump: {
    label: "Life insurance lump",
    hint: "Face amount into the nest egg the first survivor year. Today’s dollars, no CPI. $0 skips.",
    group: "partner",
    kind: "money",
  },
  currentSavings: { label: "Current retirement savings", group: "savings", kind: "money" },
  annualContribution: { label: "Annual savings until retirement", hint: "Same dollar amount each year unless you turn on the inflation toggle below.", group: "savings", kind: "money" },
  savingsGrowWithInflation: {
    label: "Raise yearly saving with inflation",
    hint: "Off = a level deposit (ordinary annuity). On = this year’s deposit rises with general inflation.",
    group: "savings",
    kind: "toggle",
  },
  partTimeAnnualIncome: { label: "Part-time / side-hustle income", hint: "Today’s dollars, after retirement.", group: "work", kind: "money" },
  partTimeStartAge: { label: "Part-time starts", group: "work", kind: "age" },
  partTimeEndAge: { label: "Part-time ends", hint: "Last year with this income.", group: "work", kind: "age" },
  partTimeAnnualInvestment: {
    label: "Additional annual savings / investment",
    hint: "Optional. Leave at 0 to skip. Same dollar amount each year during phased work.",
    group: "work",
    kind: "money",
  },
  partTimeInvestmentReturn: {
    label: "Investment return on extra savings",
    hint: "0% means extra deposits just add up (amount × years). Used only if additional savings is above 0.",
    group: "work",
    kind: "percent",
  },
  socialSecurityAnnual: { label: "Social Security / year", hint: "Today’s dollars, with COLA (rises with general inflation).", group: "income", kind: "money" },
  socialSecurityStartAge: { label: "Social Security starts", group: "income", kind: "age" },
  pensionAnnual: { label: "Pension / year", hint: "Leave at 0 to skip. COLA is on unless you turn it off.", group: "income", kind: "money" },
  pensionStartAge: { label: "Pension starts", group: "income", kind: "age" },
  pensionCola: {
    label: "Pension COLA",
    hint: "On = this pension rises with inflation. Off = a fixed annual amount.",
    group: "income",
    kind: "toggle",
  },
  lifestyleSpendToday: { label: "Lifestyle spending / year", hint: "Housing, food, travel — not medical.", group: "spending", kind: "money" },
  healthcareSpendToday: { label: "Healthcare spending / year", hint: "Premiums + out-of-pocket today.", group: "spending", kind: "money" },
  longTermCareAnnual: { label: "Long-term care / year", hint: "In-home or extra support. Skipped once nursing or CCRC rent starts.", group: "spending", kind: "money" },
  longTermCareStartAge: { label: "Long-term care starts", group: "spending", kind: "age" },
  seniorHomeRentAnnual: { label: "Senior home rental / year", hint: "Independent living. Today’s dollars.", group: "housing", kind: "money" },
  seniorHomeStartAge: { label: "Senior rental starts", group: "housing", kind: "age" },
  nursingHomeRentAnnual: { label: "Nursing home / year", hint: "Replaces senior rental from this age.", group: "housing", kind: "money" },
  nursingHomeStartAge: { label: "Nursing home starts", group: "housing", kind: "age" },
  ccrcRentAnnual: { label: "Continuing care rent / year", hint: "CCRC monthly fees, annualized. Takes priority if set.", group: "housing", kind: "money" },
  ccrcStartAge: { label: "Continuing care starts", group: "housing", kind: "age" },
  inflationRate: { label: "General inflation", group: "assumptions", kind: "percent" },
  healthcareInflationRate: { label: "Healthcare inflation", group: "assumptions", kind: "percent" },
  preRetirementReturn: {
    label: "Return before retirement",
    hint: "Grows current savings (future value) and annual deposits until full-time work ends. Deposits stay level unless the inflation toggle is on.",
    group: "savings",
    kind: "percent",
  },
  postRetirementReturn: { label: "Return in retirement", group: "assumptions", kind: "percent" },
  goGoEndAge: { label: "Go-go years end", hint: "Higher travel and activity, through this age.", group: "phases", kind: "age" },
  slowGoEndAge: { label: "Slow-go years end", hint: "Through this age, then no-go years begin.", group: "phases", kind: "age" },
  goGoLifestyleMultiplier: { label: "Go-go lifestyle factor", group: "phases", kind: "multiplier" },
  slowGoLifestyleMultiplier: { label: "Slow-go lifestyle factor", group: "phases", kind: "multiplier" },
  noGoLifestyleMultiplier: { label: "No-go lifestyle factor", group: "phases", kind: "multiplier" },
};
